using System.Security.Cryptography;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using StockStudio.Api.Domain;
using StockStudio.Api.Models;
using StockStudio.Api.Services;
using StockStudio.Api.Services.Integration;

namespace StockStudio.Api.Controllers;

[ApiController]
[Route("api/pipeline")]
public class PipelineController : ControllerBase
{
    private readonly PipelineSettings _s;
    private readonly SharePointStore _sp;
    private readonly QueueDispatcher _queue;
    private readonly IJobStore _store;
    private readonly ILogger<PipelineController> _log;

    public PipelineController(IOptions<PipelineSettings> s, SharePointStore sp, QueueDispatcher queue, IJobStore store, ILogger<PipelineController> log)
    {
        _s = s.Value;
        _sp = sp;
        _queue = queue;
        _store = store;
        _log = log;
    }

    /// <summary>Approximate depths of the pipeline queues (backlog/health). Requires a Storage connection.</summary>
    [HttpGet("queues")]
    public async Task<IActionResult> Queues(CancellationToken ct)
    {
        // The -poison queues are where the Functions runtime parks messages that failed five
        // times. They are normally empty, so anything in them is a file the pipeline gave up on.
        var names = new[]
        {
            _s.QueueName, "shrinked-image-to-classify", "images-to-send",
            $"{_s.QueueName}-poison", "images-to-send-poison",
        };
        var depths = await _queue.GetDepthsAsync(names, ct);
        return Ok(new { configured = _queue.CanEnqueue, queues = depths });
    }

    /// <summary>Locates a file across the pipeline stage libraries by exact name.</summary>
    [HttpGet("track")]
    public IActionResult Track([FromQuery] string name)
    {
        if (!_s.Enabled) return BadRequest("Pipeline disabilitata.");
        if (string.IsNullOrWhiteSpace(name)) return BadRequest("Parametro 'name' mancante.");
        try { return Ok(new { ok = true, name, stages = _sp.TrackFile(name.Trim()) }); }
        catch (Exception ex) { return Ok(new { ok = false, error = ex.Message }); }
    }

    /// <summary>
    /// Callback for the Azure pipeline (UploadFileViaSFTP → Logic App) to report a file's final
    /// publish result. Marks the matching job item as published so the dashboard closes the loop.
    /// </summary>
    [HttpPost("callback")]
    public IActionResult Callback([FromBody] PublishCallback body)
    {
        // The callback is exempt from the API-key middleware because it has its own shared secret.
        // When the integration is off, do not leave an unsigned mutation endpoint reachable.
        if (!_s.Enabled) return NotFound();

        // Optional shared secret: when configured, the pipeline must present it.
        if (!string.IsNullOrWhiteSpace(_s.CallbackSecret))
        {
            var provided = Request.Headers["X-Callback-Secret"].ToString();
            if (!CryptographicOperations.FixedTimeEquals(
                    System.Text.Encoding.UTF8.GetBytes(provided ?? ""),
                    System.Text.Encoding.UTF8.GetBytes(_s.CallbackSecret)))
                return Unauthorized();
        }

        var fileName = Path.GetFileName((body.FilePath ?? body.File ?? "").Replace('\\', '/'));
        if (string.IsNullOrWhiteSpace(fileName)) return BadRequest("Serve 'file' o 'filePath'.");

        var resolved = _store.ResolveDispatch(fileName) ?? FallbackResolve(fileName);
        if (resolved == null)
        {
            _log.LogWarning("Callback: nessun item per {File}", fileName);
            return NotFound(new { matched = false, fileName });
        }

        var job = _store.Get(resolved.Value.jobId);
        var item = job?.Items.FirstOrDefault(i => i.Id == resolved.Value.itemId);
        if (job == null || item == null) return NotFound(new { matched = false, fileName });

        var ok = body.StatusCode is null or >= 200 and < 300;
        item.PublishStatus = ok ? "published" : "publish_failed";
        item.PublishMessage = body.Message;
        item.PublishedAt = DateTime.UtcNow;
        if (ok) item.Status = "published";

        // Adopt the real metadata generated by the existing pipeline (Logic App), replacing the local placeholder.
        if (!string.IsNullOrWhiteSpace(body.Title)) item.Title = body.Title!.Trim();
        if (!string.IsNullOrWhiteSpace(body.Description)) item.Description = body.Description!.Trim();
        if (!string.IsNullOrWhiteSpace(body.Tags))
        {
            item.Keywords = body.Tags!
                .Split(new[] { ',', ';' }, StringSplitOptions.RemoveEmptyEntries)
                .Select(k => k.Trim())
                .Where(k => k.Length > 0)
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();
        }
        if (!string.IsNullOrWhiteSpace(body.Title) || !string.IsNullOrWhiteSpace(body.Tags))
            item.MetadataSource = "pipeline";

        _store.Save(job);

        return Ok(new
        {
            matched = true,
            jobId = job.Id,
            itemId = item.Id,
            status = item.PublishStatus,
            metadataApplied = !string.IsNullOrWhiteSpace(body.Title) || !string.IsNullOrWhiteSpace(body.Tags),
        });
    }

    private (string jobId, string itemId)? FallbackResolve(string fileName)
    {
        // Only consider items that were actually dispatched and are still awaiting a publish result,
        // matching on the exact dispatched file name — never on base name alone (that hit wrong items).
        foreach (var job in _store.List(200))
        {
            var item = job.Items.FirstOrDefault(i =>
                i.DispatchedAt != null && i.PublishedAt == null &&
                string.Equals(i.JpgFile, fileName, StringComparison.OrdinalIgnoreCase));
            if (item != null) return (job.Id, item.Id);
        }
        return null;
    }

    [HttpGet("status")]
    public IActionResult Status() => Ok(new
    {
        enabled = _s.Enabled,
        canEnqueue = _queue.CanEnqueue,
        siteUrl = _s.SiteUrl,
        libraryFolder = _s.LibraryFolder,
        queueName = _s.QueueName,
        dispatchFile = _s.DispatchFile,
        trigger = _queue.CanEnqueue ? "queue" : "sharepoint-logicapp",
    });

    /// <summary>Read-only: pipeline funnel — item counts across the ImagesToClassify → ImagesToSend → ImagesSent stages.</summary>
    [HttpGet("funnel")]
    public IActionResult Funnel()
    {
        if (!_s.Enabled) return BadRequest("Pipeline disabilitata.");
        try
        {
            var libs = _sp.ListDocumentLibraries();
            int CountOf(string name)
            {
                foreach (var o in libs)
                {
                    var t = o.GetType();
                    var title = t.GetProperty("title")?.GetValue(o) as string;
                    if (string.Equals(title, name, StringComparison.OrdinalIgnoreCase))
                        return Convert.ToInt32(t.GetProperty("itemCount")?.GetValue(o) ?? 0);
                }
                return 0;
            }

            var stages = new[]
            {
                new { key = "classify", label = "In attesa AI (ImagesToClassify)", count = CountOf("ImagesToClassify") },
                new { key = "send", label = "Post-AI, pre-invio (ImagesToSend)", count = CountOf("ImagesToSend") },
                new { key = "sent", label = "Pubblicati (ImagesSent)", count = CountOf("ImagesSent") },
            };
            return Ok(new { ok = true, stages, timestamp = DateTime.UtcNow.ToString("o") });
        }
        catch (Exception ex) { return Ok(new { ok = false, error = ex.Message }); }
    }

    /// <summary>Checks whether files are already published (duplicate) in ImagesSent.</summary>
    [HttpGet("duplicate")]
    public IActionResult Duplicate([FromQuery] string name)
    {
        if (!_s.Enabled) return BadRequest("Pipeline disabilitata.");
        if (string.IsNullOrWhiteSpace(name)) return BadRequest("Parametro 'name' mancante.");
        try { return Ok(new { ok = true, name, duplicate = _sp.IsAlreadyPublished(name.Trim()) }); }
        catch (Exception ex) { return Ok(new { ok = false, error = ex.Message }); }
    }

    /// <summary>Read-only SharePoint auth probe (verifies certificate + site access).</summary>
    [HttpPost("probe")]
    public IActionResult Probe()
    {
        if (!_s.Enabled) return BadRequest("Pipeline disabilitata.");
        try { return Ok(new { ok = true, web = _sp.ProbeConnection() }); }
        catch (Exception ex) { return Ok(new { ok = false, error = ex.Message }); }
    }

    /// <summary>Read-only: lists document libraries in the site to locate the pipeline drop folder.</summary>
    [HttpGet("libraries")]
    public IActionResult Libraries()
    {
        if (!_s.Enabled) return BadRequest("Pipeline disabilitata.");
        try { return Ok(new { ok = true, libraries = _sp.ListDocumentLibraries() }); }
        catch (Exception ex) { return Ok(new { ok = false, error = ex.Message }); }
    }

    /// <summary>Read-only: peeks recent file names in a folder to learn the expected input format.</summary>
    [HttpGet("peek")]
    public IActionResult Peek([FromQuery] string folder, [FromQuery] int take = 8)
    {
        if (!_s.Enabled) return BadRequest("Pipeline disabilitata.");
        try { return Ok(new { ok = true, files = _sp.ListFolderFiles(folder, take) }); }
        catch (Exception ex) { return Ok(new { ok = false, error = ex.Message }); }
    }

    /// <summary>Read-only: writable columns of a library, to confirm the pipeline fields exist.</summary>
    [HttpGet("fields")]
    public IActionResult Fields([FromQuery] string list)
    {
        if (!_s.Enabled) return BadRequest("Pipeline disabilitata.");
        try { return Ok(new { ok = true, fields = _sp.ListFields(list) }); }
        catch (Exception ex) { return Ok(new { ok = false, error = ex.Message }); }
    }
}
